### ISSUE TITLE
Attributes are also translated

### ISSUE THREAD

**Issue by justie75** [vildanbina/laravel-auto-translation#1]
The attributes (:name), (:role) are also translated into the destination language. This breaks this function.

Example:
"Change to :name": "Wijzigen in :naam"

**Comment by vildanbina** [comment]
Hi @justie75,

Thank you for reporting this! I've resolved the issue where placeholders (e.g., :name, :role) were being translated incorrectly. The fix ensures placeholders remain intact during translation.

This is now available in [v1.0.1](https://github.com/vildanbina/laravel-auto-translation/releases/tag/1.1.0)
